# Generated by Django 5.0.6 on 2025-08-27 16:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('person', 'Particulier'), ('company', 'Bedrijf')], default='person', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Belgium', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Belgium', max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('enterprise_number', models.CharField(blank=True, max_length=20)),
                ('default_print_mode', models.CharField(choices=[('logo_footer', 'Met logo & footer'), ('preprinted', 'Voorbedrukt papier')], default='logo_footer', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('valid_from_year', models.PositiveIntegerField()),
                ('valid_to_year', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('set', 'Zet prijs'), ('add', 'Tel bij'), ('multiply', 'Vermenigvuldig')], default='set', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('stackable', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('default_price_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=4)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('membership_vat', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=4)),
                ('federation_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='YearSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('prefer_billing', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, help_text='Optioneel: factureren op deze account i.p.v. gezins-/ledennaam.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoiceaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Belgium', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('membership_mode', models.CharField(blank=True, choices=[('investment', 'Met investeringsbijdrage'), ('flex', 'Flexibel')], default='investment', max_length=20)),
                ('federation_via_club', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('household_role', models.CharField(blank=True, choices=[('head', 'Gezinshoofd'), ('partner', 'Partner'), ('child', 'Kind'), ('other', 'Overig')], default='other', max_length=20)),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_billed', to='core.invoiceaccount')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.household')),
                ('household_head', models.ForeignKey(blank=True, help_text='Kies het gezinshoofd indien dit lid deel uitmaakt van een gezin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_members', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INV', 'Factuur'), ('CN', 'Creditnota')], default='INV', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Concept'), ('finalized', 'Gefinaliseerd'), ('cancelled', 'Geannuleerd')], default='draft', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('payment_reference_raw', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.household')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoiceaccount')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_households', to='core.member'),
        ),
        migrations.CreateModel(
            name='MemberAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('assigned_on', models.DateField(blank=True, null=True)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('locker', 'Kast'), ('trolley_locker', 'Kar-kast'), ('e_trolley_locker', 'Elektrische kar-kast')], max_length=30)),
                ('identifier', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('price_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=4)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=4)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='YearPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('price_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=4)),
                ('yearplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.yearplan')),
            ],
            options={
                'unique_together': {('yearplan', 'code')},
            },
        ),
    ]
