# Generated by Django 5.0.6 on 2025-08-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberasset',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberasset',
            name='assigned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberasset',
            name='released_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
