# Generated by Django 5.0.6 on 2025-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('code', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('vat_rate', models.PositiveSmallIntegerField(choices=[(0, '0%'), (6, '6%'), (12, '12%'), (21, '21%')], default=21)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jaarprijs',
                'verbose_name_plural': 'Jaarprijzen',
                'ordering': ['year', 'code'],
                'unique_together': {('year', 'code')},
            },
        ),
    ]
