# Generated by Django 5.0.6 on 2025-09-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_yearpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('code', models.CharField(help_text='YearPricing.code', max_length=40)),
                ('applies_role', models.CharField(blank=True, choices=[('IND', 'Individueel'), ('HEAD', 'Gezinshoofd'), ('PRT', 'Partner'), ('KID', 'Kind')], max_length=5)),
                ('course', models.CharField(blank=True, choices=[('CC', 'Championship'), ('P3', 'Par-3')], max_length=3)),
                ('age_bucket', models.CharField(blank=True, choices=[('KID_0_15', 'Kid t/m 15'), ('KID_16_21', 'Kid 16–21'), ('YA_22_26', 'YA 22–26'), ('YA_27_29', 'YA 27–29'), ('YA_30_35', 'YA 30–35'), ('NORMAL', 'Normaal (36–59)'), ('P60', '60 Plus'), ('P70', '70 Plus')], help_text='Leeftijdscategorie (meestal volgend jaar).', max_length=20)),
                ('federation', models.CharField(choices=[('ANY', 'Onverschillig'), ('YES', 'Ja vereist'), ('NO', 'Nee vereist')], default='ANY', help_text='Federatie alleen als YES én course=CC.', max_length=3)),
                ('invest_mode', models.CharField(choices=[('ANY', 'Onverschillig'), ('NORM', 'Normaal (in 1 keer)'), ('FLEX', 'Flex (gespreid)')], default='ANY', max_length=4)),
                ('use_next_year_age', models.BooleanField(default=True, help_text='Meestal leeftijd volgend jaar.')),
                ('flex_year_min', models.PositiveSmallIntegerField(blank=True, help_text='1..7', null=True)),
                ('flex_year_max', models.PositiveSmallIntegerField(blank=True, help_text='1..7', null=True)),
                ('bill_to', models.CharField(choices=[('SELF', 'Op eigen factuur'), ('HEAD', 'Op factuur van het gezinshoofd')], default='SELF', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=9)),
                ('desc_suffix', models.CharField(blank=True, help_text="Bijv. '(jaar 3/7)'", max_length=120)),
                ('order', models.SmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('pricing', models.ForeignKey(blank=True, help_text='Optioneel: wordt automatisch gezet op save als year+code gevonden wordt.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='core.yearpricing')),
            ],
            options={
                'verbose_name': 'Jaarregel',
                'verbose_name_plural': 'Jaarregels',
                'indexes': [models.Index(fields=['year', 'code'], name='core_yearru_year_45b947_idx'), models.Index(fields=['year', 'applies_role', 'course'], name='core_yearru_year_ef8bde_idx')],
            },
        ),
    ]
