# Generated by Django 5.0.6 on 2025-08-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_memberasset_active_memberasset_assigned_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='household_head',
            field=models.ForeignKey(blank=True, help_text='Kies het gezinshoofd indien dit lid deel uitmaakt van een gezin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_members', to='core.member'),
        ),
    ]
