# Generated by Django 5.0.6 on 2025-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_yearrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearrule',
            options={'ordering': ['year', 'order', 'code']},
        ),
        migrations.RemoveIndex(
            model_name='yearrule',
            name='core_yearru_year_45b947_idx',
        ),
        migrations.RemoveIndex(
            model_name='yearrule',
            name='core_yearru_year_ef8bde_idx',
        ),
        migrations.AlterUniqueTogether(
            name='yearrule',
            unique_together={('year', 'code', 'order')},
        ),
        migrations.AddField(
            model_name='yearrule',
            name='action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='yearrule',
            name='condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='yearrule',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='yearrule',
            name='code',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='yearrule',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='age_bucket',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='applies_role',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='bill_to',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='desc_suffix',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='federation',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='flex_year_max',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='flex_year_min',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='invest_mode',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='yearrule',
            name='use_next_year_age',
        ),
    ]
