# Generated by Django 5.0.6 on 2025-08-23 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_household_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='billing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_billed', to='core.invoiceaccount'),
        ),
    ]
