# Generated by Django 5.0.6 on 2025-09-03 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_yearrule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearrule',
            options={'ordering': ['year', 'order', 'code'], 'verbose_name': 'Jaarregel', 'verbose_name_plural': 'Jaarregels'},
        ),
        migrations.CreateModel(
            name='YearInvestScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(help_text='Leeftijd (jaren)')),
                ('role', models.CharField(choices=[('IND', 'Individueel'), ('PRT', 'Partner')], max_length=3)),
                ('amount_normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_flex_yearly', models.DecimalField(decimal_places=2, help_text='Jaarbedrag voor FLEX: (normaal * 1.17) / 7, afgerond op 2 dec.', max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Degressieve investeringsbedrag',
                'verbose_name_plural': 'Degressieve investeringsbedragen',
                'ordering': ['age', 'role'],
                'unique_together': {('age', 'role')},
            },
        ),
    ]
