# Generated by Django 5.0.6 on 2025-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_yearrule_options_yearinvestscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invest_flex_locked_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vaste jaarlijkse flex-investeringsbijdrage (berekend bij start)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='invest_flex_start_year',
            field=models.PositiveIntegerField(blank=True, help_text='Jaar waarin flex-investering startte (1/7)', null=True),
        ),
    ]
