# Generated by Django 5.0.6 on 2025-09-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_member_invest_flex_locked_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='course',
            field=models.CharField(blank=True, choices=[('CC', 'Championship Course'), ('P3', 'Par-3')], db_index=True, max_length=3, null=True),
        ),
    ]
