# Generated by Django 5.0.6 on 2025-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='GSM'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_private',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Tel. Privé'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_work',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Tel. Werk'),
        ),
    ]
