# Generated by Django 5.0.6 on 2025-09-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_member_phone_mobile_member_phone_private_and_more'),
    ]

    operations = [
    ]
