# Generated by Django 5.0.6 on 2025-09-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_backfill_phone_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceaccount',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
