# Generated by Django 5.0.6 on 2025-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_member_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
