# Generated by Django 5.0.6 on 2025-09-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_member_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='household',
        ),
        migrations.RemoveField(
            model_name='member',
            name='household',
        ),
    ]
