# Generated by Django 5.0.6 on 2025-09-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_invoice_household_remove_member_household'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Household',
        ),
    ]
