# Generated by Django 5.0.6 on 2025-09-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_drop_household_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='flex_years_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='flex_years_total',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='member',
            name='investment_years_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='investment_years_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
