# Generated by Django 5.0.6 on 2025-09-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_member_flex_years_remaining_member_flex_years_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='factureren_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gefactureerden', to='core.member', verbose_name='Factureren via'),
        ),
    ]
