# Generated by Django 5.0.6 on 2025-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_member_factureren_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='federale_bijdrage_via_spiegelven',
            field=models.BooleanField(default=True, help_text='Vink uit als dit lid de federale bijdrage via een andere club betaalt.', verbose_name='Federale bijdrage via Spiegelven'),
        ),
    ]
