# Generated by Django 5.0.6 on 2025-09-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_member_federale_bijdrage_via_spiegelven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='household_role',
            field=models.CharField(blank=True, choices=[('head', 'Gezinshoofd'), ('partner', 'Partner'), ('child', 'Kind'), ('individual', 'Individueel'), ('other', 'Overig')], default='other', max_length=20),
        ),
    ]
