# Generated by Django 5.0.6 on 2025-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_member_household_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Dagfactuur', 'verbose_name_plural': 'Dagfacturen'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='Faxnummer'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefoon'),
        ),
    ]
