# Generated by Django 5.0.6 on 2026-03-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_invoice_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importmapping',
            options={'verbose_name': 'Import Data', 'verbose_name_plural': 'Import Data'},
        ),
        migrations.AlterModelOptions(
            name='invoiceaccount',
            options={'verbose_name': 'Alternatief factuurgegevens', 'verbose_name_plural': 'Alternatief factuurgegevens'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Lid', 'verbose_name_plural': 'Leden'},
        ),
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'verbose_name': 'Organisatie profiel', 'verbose_name_plural': 'Organisatie profiel'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkten'},
        ),
        migrations.AlterModelOptions(
            name='yearsequence',
            options={'verbose_name': 'Volgnummer Factuur', 'verbose_name_plural': 'Volgnummer Factuur'},
        ),
        migrations.AlterField(
            model_name='memberasset',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
