# Generated by Django 5.0.6 on 2026-03-31 21:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_importmapping_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Jaar')),
                ('lid_cc_ind', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CC individueel')),
                ('lid_cc_prt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CC partner')),
                ('lid_cc_kid_0_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CC kind t/m 15')),
                ('lid_cc_kid_16_21', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CC kind 16–21')),
                ('lid_cc_ya_22_26', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CC YA 22–26')),
                ('lid_cc_ya_27_29', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CC YA 27–29')),
                ('lid_cc_ya_30_35', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CC YA 30–35')),
                ('p3_ind', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Par-3 individueel')),
                ('p3_prt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Par-3 partner')),
                ('p3_kid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Par-3 kind')),
                ('fed_cc_ind', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Federatie CC individueel')),
                ('fed_cc_prt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Federatie CC partner')),
                ('fed_cc_kid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Federatie CC kind/YA')),
                ('inv_ind', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Investering normaal IND')),
                ('inv_prt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Investering normaal PRT')),
                ('inv_flex_ind', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Investering flex IND (1/7)')),
                ('inv_flex_prt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Investering flex PRT (1/7)')),
                ('vst_kast', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Vestiaire kast')),
                ('kar_kln', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Karrengarage klein')),
                ('kar_elec', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Karrengarage elektrisch')),
            ],
            options={
                'verbose_name': 'Jaarlijkse prijzen',
                'verbose_name_plural': 'Jaarlijkse prijzen',
                'ordering': ['-year'],
            },
        ),
    ]
